---
title: 错误处理
categories: 

- ES5


---

无论输入，finally都会执行，所以，这个finally觉得没什么用

```
try{
    console.log(111);
    setTimeout(function() {
        throw new Error('setTimeout err');  
    }, 2000);
}catch(e){
    console.log('catch:');
    console.log(e);
}finally{
    console.log('finally');
}

console.log('after try');
```

> try catch 有一个问题，针对回调，定时任务等需要等一段时间的报错，无法处理